package com.librarySystem.corba;


/**
* com/librarySystem/corba/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./server.idl
* Thursday, 25 April, 2019 3:44:08 AM IST
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
